server:
  port: 8080
#  servlet:
#    context-path:
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_default: false
  liquibase:
    change-log: 'classpath:db/migrations/changeLog.xml'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lexed?serverTimezone=UTC
    username: lexed
    password: postgres

  thymeleaf:
    encoding: UTF-8
    check-template-location: true
    enabled: true
    servlet:
      content-type: text/html

  servlet:
    multipart:
      max-request-size: 5000
      max-file-size: 10000
      enabled: true
